name = "developer-portal-test"
main = "index.js"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "dev-test.bozza.au/*"
zone_name = "bozza.au"

[vars]
ENVIRONMENT = "test"
ACCESS_TIER = "2"
POLICY_NAME = "Developer - Standard Access"
