name = "emergency-access-test"
main = "index.js"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "emergency-test.bozza.au/*"
zone_name = "bozza.au"

[vars]
ENVIRONMENT = "test"
ACCESS_TIER = "4"
POLICY_NAME = "Admin - Emergency Access"
